{
 "title": "dash-catalogo-carros",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "TOTAL GERAL REQUEST",
   "type": "stat",
   "description": "Total de requisição  para um controller especifico",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{endpoint=\"WeatherForecast\", instance=\"app-catalogo-api:80\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USO CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"app-catalogo-api:80\", job=\"app-catalogo-api-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRO RATE",
   "type": "timeseries",
   "description": "Taxa de erro nos ultimos 5 minutos",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=\"404\"}[5m])) / sum(rate(http_request_duration_seconds_count{}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Numero de requisiçoes por endpoint no ultimo minuto",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{endpoint=\"WeatherForecast\"}[1m]))",
     "legendFormat": "WeatherForecast"
    }
   ]
  },
  {
   "title": "TOTAL REQUESTS",
   "type": "stat",
   "description": "Número de requesições no ultimo minuto",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUMERO THREADS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_num_threads{instance=\"app-catalogo-api:80\", job=\"app-catalogo-api-job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 404",
   "type": "stat",
   "description": "Numero de erros 404 no ultimo minuto",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=\"404\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "START TIME",
   "type": "stat",
   "description": "Hora da inicialização da API",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"app-catalogo-api:80\", job=\"app-catalogo-api-job\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Tempo de resposta no ultimo minuto",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{instance=\"app-catalogo-api:80\", job=\"app-catalogo-api-job\"}[1m]) / rate(http_request_duration_seconds_count{instance=\"app-catalogo-api:80\", job=\"app-catalogo-api-job\"}[1m])",
     "legendFormat": "{{endpoint}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "MEMORIA USADA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LATENCY AVERAGE",
   "type": "timeseries",
   "description": "Latencia media por minuto",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "description": "Duração media de requisição no ultimo minuto",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{endpoint=\"WeatherForecast\", code=\"200\"}[1m]) / rate(http_request_duration_seconds_count{endpoint=\"WeatherForecast\", code=\"200\"}[1m])",
     "legendFormat": "{{endpoint}} {{code}} {{method}}"
    }
   ]
  }
 ]
}